### ISSUE TITLE
Linear Search with C#

### ISSUE THREAD

**Issue by BasakDemirok** [CodeChefMUST/Algorithms#102]
I can write the code for linear search in C#, please assign it to me :)

**Comment by Taneesha-creates** [comment]
Hello @BasakDemirok , this issue has been assigned to you. No more contributors required at the moment.

# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the searching directory, navigate to `Linear Search1
2. Create the `C#` directory
3. Create the file `LinearSearch.cs`.

Here's how the final structure should look like:
- Searching
    - Linear Search
        - Algorithm.md
        - C#
            - LinearSearch.cs


### Please follow the *same* naming conventions as mentioned in this comment.

# Before you create a pull request, if you observe that the folder Heap Sort has already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.
