### ISSUE TITLE
Selection Sort with C#

### ISSUE THREAD

**Issue by BasakDemirok** [CodeChefMUST/Algorithms#109]
I can write the code, please assign it to me :)

**Comment by 22tanyabansal** [comment]
I want to work on this issue. Please assign to me.
It helps me a lot for completing my goal

**Comment by BasakDemirok** [comment]
@22tanyabansal  why don't you try to open an issue? It hepls me a lot too. You are not the only one, everyone has similar goals. I looked at the site, I researched which topics were opened, which topics are missing, what can I do. On the other hand, you came, saw my issue and added yourself. I think this is not a good approach. Please do not misunderstand me. 

> I want to work on this issue. Please assign to me. It helps me a lot for completing my goal

**Comment by Taneesha-creates** [comment]
Hello @BasakDemirok, this issue has now been assigned to you. 

Thank you for opening a new issue. Please read the README.md file for the guidelines on how to contribute.

# Important:

Here are the steps for contribution:

1. In the `Sorting` directory, navigate to `Selection Sort`.
2. Create a new directory - `C#`.
3. In this directory, write your code in - `SelectionSort.cs`

### File Structure (important):
- Sorting
    - Selection Sort (directory)
        - algorithm.md (markdown file explaining the algorithm)
        - C# (directory)
            - SelectionSort.cs (code)


### Please follow the *same* naming conventions as mentioned in this comment.

## Before you create a pull request, if you observe that the required folders have already been created, then please refrain from creating a new one, make some changes in your forked repository so that it matches with the current one and there are no conflicts.

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.
