### ISSUE TITLE
Position of an Element in an Infinite Sorted Array - Binary Search

### ISSUE THREAD

**Issue by heenathadani** [CodeChefMUST/Algorithms#131]
Kindly assign the issue to me. I'd be using the binary search algorithm for this particular question and use Java as language to solve. :)

**Comment by Taneesha-creates** [comment]
Hello @heenathadani, thank you for creating an issue, it has now been assigned to you. 

# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the `Searching` directory, and navigate to the sub-directory `Binary Search`.
2. In the Algorithm.md, please add the problem statement.
3. Move to the `Java` directory.
4. Create the file of your code in camel case.

Here's how the final structure should look like:
- Searching
    - Binary Search
        - Algorithm.md
        - Java
            - `your code.java`


### Please follow the *same* naming conventions as mentioned.

## Before you create a pull request, make some changes in your forked repository so that it matches with the current one and there are no conflicts (`git pull`).

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.
