### ISSUE TITLE
Interpolation search in C++

### ISSUE THREAD

**Issue by KaneezFatima-101** [CodeChefMUST/Algorithms#184]
Please, assign me this issue.

**Comment by Taneesha-creates** [comment]
Hello @heenathadani, thank you for creating an issue, it has now been assigned to you. 

# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the `Searching` directory, create the sub-directory `Interpolation Search`.
2. Create a file `Algorithm.md` that contains steps for the algorithm
3. Create the `C++` directory.
4. Create the file of your code in camel case.

Here's how the final structure should look like:
- Searching
    - Interpolation Search
        - Algorithm.md
        - C++
            - `InterpolationSearch.cpp`


### Please follow the *same* naming conventions as mentioned.

## Before you create a pull request, make some changes in your forked repository so that it matches with the current one and there are no conflicts (`git pull`).

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.
