### ISSUE TITLE
Height of Binary Tree in C++

### ISSUE THREAD

**Issue by vinayassrao** [CodeChefMUST/Algorithms#99]
I would like to work on this

**Comment by 22tanyabansal** [comment]
I want to work on this issue, please assign to me.

**Comment by vinayassrao** [comment]
@Taneesha-creates can u please assign me this

**Comment by Taneesha-creates** [comment]
Hello, @vinayassrao, this issue cannot be assigned to you. Our repository focuses on algorithms, and only questions that require the implementation of said algorithms can be added.

If you are implementing it using a traversal, please drop in a comment and we will assign it to you along with the guidelines.

**Comment by vinayassrao** [comment]
@Taneesha-creates ,Thank u for replying ,I can write this code using **level order traversal** of a binary tree.That would erase any concerns you have right

**Comment by Taneesha-creates** [comment]
Hey @vinayassrao, thank you for your patience. This issue is now assigned to you.

# Important:

Before you start your work on this issue, **make sure** you go through the README.md and Contribution Guidelines.md

## File structure:
1. In the `Traversal Algorithms` directory, and navigate to the sub-directory `Tree Traversals`.
2. Move to the `Level Order Traversal - Binary Tree` directory.
3. In the file - `Algorithm.md` add your problem statement.
4. In the C++ directory, write your code. 

Here's how the final structure should look like:
- Traversal Algorithms
    - Tree Traversals
        - Level Order Traversal - Binary Tree
            - C++
                - `HeightOfTree.cpp`
            - Algorithm.md


### Please follow the *same* naming conventions as mentioned.

## Before you create a pull request, make some changes in your forked repository so that it matches with the current one and there are no conflicts (do `git pull`)

# Note that all PRs are being checked for plagiarism, please refrain from indulging in any crooked means, we trust you!

We thank you for your contribution and time and we hope that you enjoy contributing to open source.
